[package]
name = "modsurfer-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.22"
clap = { version = "4.0.18" }
futures = "0.3.25"
log = "0.4.17"
protobuf = "3.2.0"
reqwest = "0.11.12"
tokio = { version = "1.21.2", features = ["full"] }
url = "2.3.1"

[[bin]]
name = "modsurfer"
path = "src/main.rs"
