name: Modsurfer Action
on: [push, pull_request, workflow_dispatch]
jobs:
  check-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: modsurfer validate
        uses: dylibso/modsurfer@action
        with:
            command: validate -p test/spidermonkey.wasm -c test/mod.yaml