name: Modsurfer Action
on: [push, pull_request, workflow_dispatch]
jobs:
  check-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: modsurfer validate
        uses: dylibso/modsurfer-validate-action@main
        with:
            path: test/spidermonkey.wasm
            check: test/mod.yaml