name: Publish ghcr.io/dylibso/modsurfer:latest

on:
  push:
    branches:
      - main

jobs:
  push_to_ghcr:
    name: Push to GitHub container registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build, tag, & push the latest image
        run: |
          docker build . --tag ghcr.io/dylibso/modsurfer:latest
          docker run --rm ghcr.io/dylibso/modsurfer:latest -V
          docker push ghcr.io/dylibso/modsurfer:latest