name: Publish ghcr.io/dylibso/modsurfer:latest

on:
  push:
    branches:
      - main

jobs:
  push_to_ghcr:
    name: Push to GitHub container registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build, tag, & push the latest image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: "ghcr.io/modsurfer:latest"
          cache-from: type=gha
          cache-to: type=gha,mode=max